export const GET_ALLMOVIES_API_REQUESTED = "GET_ALLMOVIES_API_REQUESTED";
export const GET_ALLMOVIES_API_SUCCESSED = "GET_ALLMOVIES_API_SUCCESSED";
export const GET_ALLMOVIES_API_FAILED = "GET_ALLMOVIES_API_FAILED";
export const GET_FILTERED_DATA = "GET_FILTERED_DATA"