export const GET_MOVIES_DETAILS_API_REQUESTED = "GET_MOVIES_DETAILS_API_REQUESTED";
export const GET_MOVIES_DETAILS_API_SUCCESSED = "GET_MOVIES_DETAILS_API_SUCCESSED";
export const GET_MOVIES_DETAILS_API_FAILED = "GET_MOVIES_DETAILS_API_FAILED";